apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: sealed-secrets-controller-deployment-rule
  namespace: sealed-secrets
spec:
  clusterSelector:
    matchExpressions:
      - key: vendor
        operator: In
        values:
          - OpenShift
      - key: local-cluster
        operator: DoesNotExist
  clusterConditions: []
