apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: sealed-secrets-controller-deployment
  namespace: sealed-secrets
  annotations:
    policy.open-cluster-management.io/standards: NIST 800-53, NIST-CSF
    policy.open-cluster-management.io/categories: CM Configuration Management, PR.IP Information Protection Processes and Procedures
    policy.open-cluster-management.io/controls: CM-2 Baseline Configuration, PR.IP-1 Baseline Configuration
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: sealed-secrets-namespace
        spec:
          remediationAction: enforce
          severity: high
          namespaceSelector:
            exclude:
              - kube-*
            include:
              - default
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: sealed-secrets
                spec: {}
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: sealed-secrets-custom-key
        spec:
          remediationAction: enforce
          severity: high
          namespaceSelector:
            exclude:
              - kube-*
            include:
              - default
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                data:
                  tls.crt: '{{hub fromSecret "sealed-secrets" "sealed-secrets-custom-key" "tls.crt" hub}}'
                  tls.key: '{{hub fromSecret "sealed-secrets" "sealed-secrets-custom-key" "tls.key" hub}}'
                kind: Secret
                metadata:
                  labels:
                    manager: controller
                    operation: Update
                    sealedsecrets.bitnami.com/sealed-secrets-key: active
                  name: sealed-secrets-custom-key
                  namespace: sealed-secrets
                type: kubernetes.io/tls
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: sealed-secrets-key-admin-role
        spec:
          remediationAction: enforce
          severity: high
          namespaceSelector:
            exclude:
              - kube-*
            include:
              - default
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: rbac.authorization.k8s.io/v1
                kind: Role
                metadata:
                  annotations: {}
                  labels:
                    name: sealed-secrets-key-admin
                  name: sealed-secrets-key-admin
                  namespace: sealed-secrets
                rules:
                - apiGroups:
                  - ""
                  resources:
                  - secrets
                  verbs:
                  - create
                  - list
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: sealed-secrets-controller-sap-cluster-role
        spec:
          remediationAction: enforce
          severity: high
          namespaceSelector:
            exclude:
              - kube-*
            include:
              - default
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: rbac.authorization.k8s.io/v1
                kind: ClusterRole
                metadata:
                  annotations:
                    openshift.io/description: "Role-Based Access to SCCs for Sealed Secrets"
                  name: sealed-secrets-controller-sap
                  namespace: sealed-secrets
                rules:
                - apiGroups:
                  - security.openshift.io 
                  resources:
                  - securitycontextconstraints 
                  verbs:
                  - use
                  resourceNames:
                  - privileged
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: sealed-secrets-controller-sap-role-binding
        spec:
          remediationAction: enforce
          severity: high
          namespaceSelector:
            exclude:
              - kube-*
            include:
              - default
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: rbac.authorization.k8s.io/v1
                kind: RoleBinding
                metadata:
                  name: sealed-secrets-controller-sap
                  namespace: sealed-secrets
                subjects:
                - kind: ServiceAccount
                  name: sealed-secrets-controller
                roleRef:
                  kind: ClusterRole
                  apiGroup: rbac.authorization.k8s.io
                  name: sealed-secrets-controller-sap
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: sealed-secrets-controller-role-binding
        spec:
          remediationAction: enforce
          severity: high
          namespaceSelector:
            exclude:
              - kube-*
            include:
              - default
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: rbac.authorization.k8s.io/v1
                kind: RoleBinding
                metadata:
                  annotations: {}
                  labels:
                    name: sealed-secrets-controller
                  name: sealed-secrets-controller
                  namespace: sealed-secrets
                roleRef:
                  apiGroup: rbac.authorization.k8s.io
                  kind: Role
                  name: sealed-secrets-key-admin
                subjects:
                - kind: ServiceAccount
                  name: sealed-secrets-controller
                  namespace: sealed-secrets
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: sealed-secrets-controller-cluster-role-binding
        spec:
          remediationAction: enforce
          severity: high
          namespaceSelector:
            exclude:
              - kube-*
            include:
              - default
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: rbac.authorization.k8s.io/v1
                kind: ClusterRoleBinding
                metadata:
                  annotations: {}
                  labels:
                    name: sealed-secrets-controller
                  name: sealed-secrets-controller
                roleRef:
                  apiGroup: rbac.authorization.k8s.io
                  kind: ClusterRole
                  name: secrets-unsealer
                subjects:
                - kind: ServiceAccount
                  name: sealed-secrets-controller
                  namespace: sealed-secrets
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: sealed-secrets-controller
        spec:
          remediationAction: enforce
          severity: high
          namespaceSelector:
            exclude:
              - kube-*
            include:
              - default
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: ServiceAccount
                metadata:
                  annotations: {}
                  labels:
                    name: sealed-secrets-controller
                  name: sealed-secrets-controller
                  namespace: sealed-secrets
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: sealed-secrets-crd
        spec:
          remediationAction: enforce
          severity: high
          namespaceSelector:
            exclude:
              - kube-*
            include:
              - default
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: apiextensions.k8s.io/v1
                kind: CustomResourceDefinition
                metadata:
                  name: sealedsecrets.bitnami.com
                spec:
                  conversion:
                    strategy: None
                  group: bitnami.com
                  names:
                    kind: SealedSecret
                    listKind: SealedSecretList
                    plural: sealedsecrets
                    singular: sealedsecret
                  scope: Namespaced
                  versions:
                  - name: v1alpha1
                    schema:
                      openAPIV3Schema:
                        properties:
                          spec:
                            type: object
                            x-kubernetes-preserve-unknown-fields: true
                          status:
                            x-kubernetes-preserve-unknown-fields: true
                        type: object
                    served: true
                    storage: true
                    subresources:
                      status: {}
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: sealed-secrets-service-proxier-role-binding
        spec:
          remediationAction: enforce
          severity: high
          namespaceSelector:
            exclude:
              - kube-*
            include:
              - default
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: rbac.authorization.k8s.io/v1
                kind: RoleBinding
                metadata:
                  annotations: {}
                  labels:
                    name: sealed-secrets-service-proxier
                  name: sealed-secrets-service-proxier
                  namespace: sealed-secrets
                roleRef:
                  apiGroup: rbac.authorization.k8s.io
                  kind: Role
                  name: sealed-secrets-service-proxier
                subjects:
                - apiGroup: rbac.authorization.k8s.io
                  kind: Group
                  name: system:authenticated
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: sealed-secrets-service-proxier-role
        spec:
          remediationAction: enforce
          severity: high
          namespaceSelector:
            exclude:
              - kube-*
            include:
              - default
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: rbac.authorization.k8s.io/v1
                kind: Role
                metadata:
                  annotations: {}
                  labels:
                    name: sealed-secrets-service-proxier
                  name: sealed-secrets-service-proxier
                  namespace: sealed-secrets
                rules:
                - apiGroups:
                  - ""
                  resourceNames:
                  - 'http:sealed-secrets-controller:'
                  - sealed-secrets-controller
                  resources:
                  - services/proxy
                  verbs:
                  - create
                  - get
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: secrets-unsealer-cluster-role
        spec:
          remediationAction: enforce
          severity: high
          namespaceSelector:
            exclude:
              - kube-*
            include:
              - default
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: rbac.authorization.k8s.io/v1
                kind: ClusterRole
                metadata:
                  annotations: {}
                  labels:
                    name: secrets-unsealer
                  name: secrets-unsealer
                rules:
                - apiGroups:
                  - bitnami.com
                  resources:
                  - sealedsecrets
                  verbs:
                  - get
                  - list
                  - watch
                - apiGroups:
                  - bitnami.com
                  resources:
                  - sealedsecrets/status
                  verbs:
                  - update
                - apiGroups:
                  - ""
                  resources:
                  - secrets
                  verbs:
                  - get
                  - create
                  - update
                  - delete
                - apiGroups:
                  - ""
                  resources:
                  - events
                  verbs:
                  - create
                  - patch
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: sealed-secrets-controller-deployment
        spec:
          remediationAction: enforce
          severity: high
          namespaceSelector:
            exclude:
              - kube-*
            include:
              - default
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: apps/v1
                kind: Deployment
                metadata:
                  labels:
                    name: sealed-secrets-controller
                  name: sealed-secrets-controller
                  namespace: sealed-secrets
                spec:
                  minReadySeconds: 30
                  progressDeadlineSeconds: 600
                  replicas: 1
                  revisionHistoryLimit: 10
                  selector:
                    matchLabels:
                      name: sealed-secrets-controller
                  strategy:
                    rollingUpdate:
                      maxSurge: 25%
                      maxUnavailable: 25%
                    type: RollingUpdate
                  template:
                    metadata:
                      labels:
                        name: sealed-secrets-controller
                    spec:
                      containers:
                      - command:
                        - controller
                        - --update-status
                        env:
                        - name: SEALED_SECRETS_UPDATE_STATUS
                          value: "1"
                        image: docker.io/bitnami/sealed-secrets-controller:v0.17.5
                        imagePullPolicy: Always
                        livenessProbe:
                          failureThreshold: 3
                          httpGet:
                            path: /healthz
                            port: http
                            scheme: HTTP
                          periodSeconds: 10
                          successThreshold: 1
                          timeoutSeconds: 1
                        name: sealed-secrets-controller
                        ports:
                        - containerPort: 8080
                          name: http
                          protocol: TCP
                        readinessProbe:
                          failureThreshold: 3
                          httpGet:
                            path: /healthz
                            port: http
                            scheme: HTTP
                          periodSeconds: 10
                          successThreshold: 1
                          timeoutSeconds: 1
                        resources: {}
                        securityContext:
                          readOnlyRootFilesystem: true
                          runAsNonRoot: true
                          runAsUser: 1001
                        terminationMessagePath: /dev/termination-log
                        terminationMessagePolicy: File
                        volumeMounts:
                        - mountPath: /tmp
                          name: tmp
                      dnsPolicy: ClusterFirst
                      restartPolicy: Always
                      schedulerName: default-scheduler
                      securityContext:
                        fsGroup: 65534
                      serviceAccount: sealed-secrets-controller
                      serviceAccountName: sealed-secrets-controller
                      terminationGracePeriodSeconds: 30
                      volumes:
                      - emptyDir: {}
                        name: tmp
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: sealed-secrets-controller-service
        spec:
          remediationAction: enforce
          severity: high
          namespaceSelector:
            exclude:
              - kube-*
            include:
              - default
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Service
                metadata:
                  annotations: {}
                  labels:
                    name: sealed-secrets-controller
                  name: sealed-secrets-controller
                  namespace: sealed-secrets
                spec:
                  ports:
                  - port: 8080
                    targetPort: 8080
                  selector:
                    name: sealed-secrets-controller
                  type: ClusterIP
