apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alice-minimal
  namespace: umbrella-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/compare-options: IgnoreExtraneous
  labels:
    gitops.ownedBy: cluster-config
spec:
  destination:
    namespace: umbrella-gitops
    server: https://kubernetes.default.svc
  project: cluster-config
  source:
    path: manifests/clusters/alice/argocd/apps/cluster-minimal/base
    repoURL: https://github.com/nasx/umbrella-gitops.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
