apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: spark-shot-subscription
  namespace: umbrella-gitops
  annotations:
      apps.open-cluster-management.io/git-branch: main
      apps.open-cluster-management.io/github-path: manifests/clusters/spark-shot/advanced-cluster-management-policies/base
      apps.open-cluster-management.io/reconcile-option: merge
spec:
  channel: umbrella-gitops/umbrella-gitops
  placement:
    local: true
