apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: spark-shot-placement-rule
  namespace: umbrella-gitops
spec:
  clusterConditions:
    - type: ManagedClusterConditionAvailable
      status: "True"
  clusterSelector:
    matchExpressions:
    - key: name
      operator: In
      values:
      - spark-shot
