apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: vmware-rwo-registry
  namespace: umbrella-gitops
  annotations:
    policy.open-cluster-management.io/standards: NIST-CSF
    policy.open-cluster-management.io/categories: PR.IP Information Protection Processes and Procedures
    policy.open-cluster-management.io/controls: PR.IP-1 Baseline Configuration
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: rwo-pvc
      spec:
        remediationAction: enforce
        severity: High
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: v1
            kind: PersistentVolumeClaim
            metadata:
              name: image-registry-storage
              namespace: openshift-image-registry
            spec:
              accessModes:
              - ReadWriteOnce
              resources:
                requests:
                  storage: 100Gi
              storageClassName: thin
              volumeMode: Filesystem
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: registry-config
      spec:
        remediationAction: enforce
        severity: High
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: imageregistry.operator.openshift.io/v1
            kind: Config
            metadata:
              name: cluster
            spec:
              logLevel: Normal
              managementState: Managed
              operatorLogLevel: Normal
              replicas: 1
              rolloutStrategy: Recreate
              storage:
                managementState: Unmanaged
                pvc:
                  claim: image-registry-storage
