apiVersion: redhatcop.redhat.io/v1alpha1
kind: ResourceLocker
metadata:
  name: apiserver-patch
  namespace: resource-locker-config
spec:
  serviceAccountRef:
    name: resource-locker-apiserver-sa
  patches:
  - targetObjectRef:
      apiVersion: config.openshift.io/v1
      kind: APIServer
      name: cluster
    patchTemplate: |
      spec:
        servingCerts:
          namedCertificates:
          - names:
            - api.alice.lab.uc2.io
            servingCertificate:
              name: api-cert
    patchType: application/merge-patch+json
    id: apiserver-patch