apiVersion: redhatcop.redhat.io/v1alpha1
kind: Patch
metadata:
  name: apiserver-patch
  namespace: patch-operator-config
spec:
  patches:
    apiserver-patch:
      patchTemplate: |
        spec:
          servingCerts:
            namedCertificates:
            - names:
              - api.alice.lab.uc2.io
              servingCertificate:
                name: api-cert
      patchType: application/merge-patch+json
      targetObjectRef:
        apiVersion: config.openshift.io/v1
        kind: APIServer
        name: cluster
  serviceAccountRef:
    name: patch-operator-apiserver-sa
