apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: resource-locker-ingress-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: resource-locker-ingress-role
subjects:
- kind: ServiceAccount
  name: resource-locker-ingress-sa
  namespace: resource-locker-config