apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: resource-locker-apiserver-role
  namespace: resource-locker-config
rules:
- apiGroups:
  - config.openshift.io
  resources:
  - apiserver
  - apiservers
  verbs:
  - list
  - get
  - watch
  - create
  - update
  - patch