apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: resource-locker-registry-role
  namespace: resource-locker-config
rules:
- apiGroups:
  - imageregistry.operator.openshift.io
  resources:
  - config
  - configs
  verbs:
  - list
  - get
  - watch
  - create
  - update
  - patch