# AMI ID References:
# ami-0e232a0dc0468fb1f - Microsoft Windows Server 2019 Base with Containers
# ami-046fe691f52a953f9 - Red Hat CoreOS - OpenShift 4 410.8.20190520.0

machinesets:
  - ami: ami-0e232a0dc0468fb1f
    blockDevices:
    - ebs:
        iops: 0
        volumeSize: 120
        volumeType: gp2
    instance_type: m5a.large
    machine_role: worker
    machine_type: worker
    name: windows-worker
    node_role: node-role.kubernetes.io/worker
    os: Windows
    region: us-east-1
    replicas: 1
    subnets:
      - ckeller-acm-openshift-vpn-us-east-1a-private
    tags:
      - name: "kubernetes.io/cluster/{{ cluster_info.resources[0].status.infrastructureName }}"
        value: owned
      - name: Owner
        value: ckeller@redhat.com
      - name: DeleteBy
        value: NEVER
      - name: AlwaysUp
        value: true
    user_data_secret: windows-user-data
    zone: us-east-1a
  - ami: ami-046fe691f52a953f9
    blockDevices:
    - ebs:
        iops: 0
        volumeSize: 120
        volumeType: gp2
    instance_type: m5a.2xlarge
    machine_role: ocs
    machine_type: ocs
    name: ocs-node
    node_role: node-role.kubernetes.io/ocs
    os: linux
    region: us-east-1
    replicas: 3
    subnets:
      - ckeller-acm-openshift-vpn-us-east-1a-private
    tags:
      - name: "kubernetes.io/cluster/{{ cluster_info.resources[0].status.infrastructureName }}"
        value: owned
      - name: Owner
        value: ckeller@redhat.com
      - name: DeleteBy
        value: NEVER
      - name: AlwaysUp
        value: true
    user_data_secret: worker-user-data
    zone: us-east-1a