# AMI ID References:
# ami-0e232a0dc0468fb1f - Microsoft Windows Server 2019 Base with Containers
# ami-0d5f9982f029fbc14 - Red Hat CoreOS - OpenShift 4 rhcos-47.83.202102090044-0

machinesets:
  - ami: ami-0e232a0dc0468fb1f
    blockDevices:
    - ebs:
        iops: 0
        volumeSize: 120
        volumeType: gp2
    instance_type: m5a.large
    machine_role: worker
    machine_type: worker
    name: windows-worker
    node_labels:
      node-role.kubernetes.io/worker: ""
    os: Windows
    region: us-east-1
    replicas: 1
    subnets:
      - ckeller-acm-openshift-vpn-us-east-1a-private
    tags:
      - name: "kubernetes.io/cluster/{{ cluster_info.resources[0].status.infrastructureName }}"
        value: owned
      - name: Owner
        value: ckeller@redhat.com
      - name: DeleteBy
        value: NEVER
      - name: AlwaysUp
        value: true
    user_data_secret: windows-user-data
    zone: us-east-1a
  - ami: ami-0d5f9982f029fbc14
    blockDevices:
    - ebs:
        iops: 0
        volumeSize: 120
        volumeType: gp2
    instance_type: m5.2xlarge
    machine_role: worker
    machine_type: worker
    name: infra
    node_labels:
      cluster.ocs.openshift.io/openshift-storage: ""
      node-role.kubernetes.io/infra: ""
    region: us-east-1
    replicas: 3
    subnets:
      - ckeller-acm-openshift-vpn-us-east-1a-private
    tags:
      - name: "kubernetes.io/cluster/{{ cluster_info.resources[0].status.infrastructureName }}"
        value: owned
      - name: Owner
        value: ckeller@redhat.com
      - name: DeleteBy
        value: NEVER
      - name: AlwaysUp
        value: true
    user_data_secret: worker-user-data
    zone: us-east-1a