
aws_region: us-east-1
aws_zone: us-east-1a

aws_instance_type: m5a.large

# Microsoft Windows Server 2019 Base with Containers
windows_ami_id: ami-0e232a0dc0468fb1f

wmco_namespace: windows-machine-api-operator