apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfigPool
metadata:
  name: odf
spec:
  machineConfigSelector:
    matchExpressions:
      - { key: machineconfiguration.openshift.io/role, operator: In, values: [worker,odf] }
  maxUnavailable: 1
  nodeSelector:
    matchLabels:
      node-role.kubernetes.io/odf: ""
  paused: false
