apiVersion: redhatcop.redhat.io/v1alpha1
kind: ResourceLocker
metadata:
  name: cnv-node2-patch
  namespace: resource-locker-config
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "2"
spec:
  serviceAccountRef:
    name: resource-locker-node-sa
  patches:
  - targetObjectRef:
      apiVersion: v1
      kind: Node
      name: cnv-node2.alice.lab.uc2.io
    patchTemplate: |
      metadata:
        labels:
          node-role.kubernetes.io/worker: null
          node-role.kubernetes.io/cnv: ""
    patchType: application/strategic-merge-patch+json
    id: cnv-node2-label