apiVersion: redhatcop.redhat.io/v1alpha1
kind: ResourceLocker
metadata:
  name: infra-node1-patch
  namespace: resource-locker-config
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "2"
spec:
  serviceAccountRef:
    name: resource-locker-node-sa
  patches:
  - targetObjectRef:
      apiVersion: v1
      kind: Node
      name: infra-node1.alice.ocp.pwc.umbrella.local
    patchTemplate: |
      metadata:
        labels:
          node-role.kubernetes.io/worker: null
          node-role.kubernetes.io/infra: ""
    patchType: application/strategic-merge-patch+json
    id: infra-node1-label