apiVersion: redhatcop.redhat.io/v1alpha1
kind: Patch
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "2"
  name: node-label-patch
  namespace: patch-operator-config
spec:
  patches:
    cnv-node0-patch:
      patchTemplate: |
        metadata:
          labels:
            node-role.kubernetes.io/cnv: ""
            node-role.kubernetes.io/worker: null
      patchType: application/merge-patch+json
      targetObjectRef:
        apiVersion: v1
        kind: Node
        name: cnv-node0.alice.lab.uc2.io
    cnv-node1-patch:
      patchTemplate: |
        metadata:
          labels:
            node-role.kubernetes.io/cnv: ""
            node-role.kubernetes.io/worker: null
      patchType: application/merge-patch+json
      targetObjectRef:
        apiVersion: v1
        kind: Node
        name: cnv-node1.alice.lab.uc2.io
    cnv-node2-patch:
      patchTemplate: |
        metadata:
          labels:
            node-role.kubernetes.io/cnv: ""
            node-role.kubernetes.io/worker: null
      patchType: application/merge-patch+json
      targetObjectRef:
        apiVersion: v1
        kind: Node
        name: cnv-node2.alice.lab.uc2.io
    infra-node0-patch:
      patchTemplate: |
        metadata:
          labels:
            node-role.kubernetes.io/infra: ""
            node-role.kubernetes.io/worker: null
      patchType: application/merge-patch+json
      targetObjectRef:
        apiVersion: v1
        kind: Node
        name: infra-node0.alice.lab.uc2.io
    infra-node1-patch:
      patchTemplate: |
        metadata:
          labels:
            node-role.kubernetes.io/infra: ""
            node-role.kubernetes.io/worker: null
      patchType: application/merge-patch+json
      targetObjectRef:
        apiVersion: v1
        kind: Node
        name: infra-node1.alice.lab.uc2.io
    infra-node2-patch:
      patchTemplate: |
        metadata:
          labels:
            node-role.kubernetes.io/infra: ""
            node-role.kubernetes.io/worker: null
      patchType: application/merge-patch+json
      targetObjectRef:
        apiVersion: v1
        kind: Node
        name: infra-node2.alice.lab.uc2.io
    ocs-node0-patch:
      patchTemplate: |
        metadata:
          labels:
            cluster.ocs.openshift.io/openshift-storage: ""
            node-role.kubernetes.io/ocs: ""
            node-role.kubernetes.io/worker: null
      patchType: application/merge-patch+json
      targetObjectRef:
        apiVersion: v1
        kind: Node
        name: ocs-node0.alice.lab.uc2.io
    ocs-node1-patch:
      patchTemplate: |
        metadata:
          labels:
            cluster.ocs.openshift.io/openshift-storage: ""
            node-role.kubernetes.io/ocs: ""
            node-role.kubernetes.io/worker: null
      patchType: application/merge-patch+json
      targetObjectRef:
        apiVersion: v1
        kind: Node
        name: ocs-node1.alice.lab.uc2.io
    ocs-node2-patch:
      patchTemplate: |
        metadata:
          labels:
            cluster.ocs.openshift.io/openshift-storage: ""
            node-role.kubernetes.io/ocs: ""
            node-role.kubernetes.io/worker: null
      patchType: application/merge-patch+json
      targetObjectRef:
        apiVersion: v1
        kind: Node
        name: ocs-node2.alice.lab.uc2.io
  serviceAccountRef:
    name: patch-operator-node-sa
