apiVersion: redhatcop.redhat.io/v1alpha1
kind: Patch
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "2"
  name: node-label-patch
  namespace: patch-operator-config
spec:
  patches:
    infra0-patch:
      patchTemplate: |
        metadata:
          labels:
            node-role.kubernetes.io/infra: ""
            node-role.kubernetes.io/worker: null
      patchType: application/merge-patch+json
      targetObjectRef:
        apiVersion: v1
        kind: Node
        name: infra0.alice.lab.uc2.io
    infra1-patch:
      patchTemplate: |
        metadata:
          labels:
            node-role.kubernetes.io/infra: ""
            node-role.kubernetes.io/worker: null
      patchType: application/merge-patch+json
      targetObjectRef:
        apiVersion: v1
        kind: Node
        name: infra1.alice.lab.uc2.io
    infra2-patch:
      patchTemplate: |
        metadata:
          labels:
            node-role.kubernetes.io/infra: ""
            node-role.kubernetes.io/worker: null
      patchType: application/merge-patch+json
      targetObjectRef:
        apiVersion: v1
        kind: Node
        name: infra2.alice.lab.uc2.io
    odf0-patch:
      patchTemplate: |
        metadata:
          labels:
            cluster.ocs.openshift.io/openshift-storage: ""
            node-role.kubernetes.io/ocs: ""
            node-role.kubernetes.io/worker: null
      patchType: application/merge-patch+json
      targetObjectRef:
        apiVersion: v1
        kind: Node
        name: odf0.alice.lab.uc2.io
    odf1-patch:
      patchTemplate: |
        metadata:
          labels:
            cluster.ocs.openshift.io/openshift-storage: ""
            node-role.kubernetes.io/ocs: ""
            node-role.kubernetes.io/worker: null
      patchType: application/merge-patch+json
      targetObjectRef:
        apiVersion: v1
        kind: Node
        name: odf1.alice.lab.uc2.io
    odf2-patch:
      patchTemplate: |
        metadata:
          labels:
            cluster.ocs.openshift.io/openshift-storage: ""
            node-role.kubernetes.io/ocs: ""
            node-role.kubernetes.io/worker: null
      patchType: application/merge-patch+json
      targetObjectRef:
        apiVersion: v1
        kind: Node
        name: odf2.alice.lab.uc2.io
  serviceAccountRef:
    name: patch-operator-node-sa
