apiVersion: v1
kind: Node
metadata:
  name: ocs-node1.alice.ocp.pwc.umbrella.local
  labels:
    node-role.kubernetes.io/worker: null
    node-role.kubernetes.io/ocs: ""
    cluster.ocs.openshift.io/openshift-storage: ""
