apiVersion: redhatcop.redhat.io/v1alpha1
kind: Patch
metadata:
  name: ingress-controller-patch
  namespace: patch-operator-config
spec:
  patches:
    ingress-controller-patch:
      patchTemplate: |
        spec:
          replicas: 3
          defaultCertificate:
            name: wildcard-cert
          nodePlacement:
            nodeSelector:
              matchLabels:
                node-role.kubernetes.io/infra: ""
      patchType: application/merge-patch+json
      targetObjectRef:
        apiVersion: operator.openshift.io/v1
        kind: IngressController
        name: default
        namespace: openshift-ingress-operator
  serviceAccountRef:
    name: patch-operator-ingress-sa
