- name: Wait for WMCO
  community.kubernetes.k8s_info:
    api_key: "{{ lookup('file', '/var/run/secrets/kubernetes.io/serviceaccount/token') }}"
    api_version: v1
    ca_cert: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    host: https://kubernetes.default.svc
    kind: Pod
    label_selectors:
      - name=windows-machine-config-operator
    namespace: "{{ wmco_namespace }}"
  delay: 10
  register: pod
  retries: 60
  until:
    - pod.resources[0].status.phase == "Running"

- name: Query Cluster Infrastructure Name
  community.kubernetes.k8s_info:
    api_key: "{{ lookup('file', '/var/run/secrets/kubernetes.io/serviceaccount/token') }}"
    api_version: config.openshift.io/v1
    ca_cert: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    host: https://kubernetes.default.svc
    kind: Infrastructure
    name: cluster
  register: cluster_info

- name: Debug Infrastructure Name
  ansible.builtin.debug:
    msg: "{{ cluster_info.resources[0].status.infrastructureName }}"
    verbosity: 1

- name: Set Cluster infrastructure_name
  community.kubernetes.k8s:
    api_key: "{{ lookup('file', '/var/run/secrets/kubernetes.io/serviceaccount/token') }}"
    ca_cert: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    definition: "{{ lookup('template', 'templates/machineset.yaml.j2') | from_yaml }}"
    state: present