apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: rockfort-subscription
  namespace: umbrella-gitops
  labels:
    app: rockfort
  annotations:
      apps.open-cluster-management.io/git-branch: main
      apps.open-cluster-management.io/github-path: manifests/clusters/rockfort/argocd/apps/rockfort/base
      apps.open-cluster-management.io/reconcile-option: merge
spec:
  channel: umbrella-gitops/umbrella-gitops
  placement:
    placementRef:
      kind: PlacementRule
      name: placement-rule-rockfort