apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: open-cluster-management-operatorgroup
  namespace: open-cluster-management
spec:
  targetNamespaces:
    - open-cluster-management