apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: open-cluster-management-subscription
  namespace: open-cluster-management
spec:
  channel: release-2.3
  name: advanced-cluster-management
  source: redhat-operators
  sourceNamespace: openshift-marketplace