apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ansible-runner-app.yaml
  - resource-locker-app.yaml
  - registry-app.yaml
  - oauth-app.yaml
  - sealed-secrets-app.yaml
