apiVersion: redhatcop.redhat.io/v1alpha1
kind: ResourceLocker
metadata:
  name: proxy-patch
  namespace: resource-locker-config
spec:
  serviceAccountRef:
    name: resource-locker-proxy-sa
  patches:
  - targetObjectRef:
      apiVersion: config.openshift.io/v1
      kind: Proxy
      name: cluster
    patchTemplate: |
      spec:
        trustedCA:
          name: user-ca-bundle
    patchType: application/merge-patch+json
    id: proxy-patch