apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: securedcluster-deployment-placement
  namespace: stackrox
spec:
  clusterSelector:
    matchExpressions:
      - key: vendor
        operator: In
        values:
          - OpenShift
      - key: local-cluster
        operator: DoesNotExist
  clusterConditions: []
