apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../machine-config-pools/cnv/base
  - ../../../../machine-config-pools/ocs/base
  - ../../../../machine-config-pools/infra/base