apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - apiserver-app.yaml
  - ingress-controller-app.yaml
  - machine-config-pools-app.yaml
  - node-labels-app.yaml
  - resource-locker-app.yaml
  - sealed-secrets-app.yaml
  - vmware-storage-classes-app.yaml
