apiVersion: automationcontroller.ansible.com/v1beta1
kind: AutomationController
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "5"    
  name: automation-controller
  namespace: aap
spec:
  admin_user: admin
  create_preload_data: true
  garbage_collect_secrets: false
  image_pull_policy: IfNotPresent
  ingress_type: Route
  projects_persistence: true
  postgres_storage_class: ocs-storagecluster-cephfs
  projects_storage_access_mode: ReadWriteMany
  projects_storage_class: ocs-storagecluster-cephfs
  projects_storage_size: 8Gi
  replicas: 2
  route_tls_termination_mechanism: Edge
  task_privileged: false
