apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfigPool
metadata:
  name: cnv
spec:
  machineConfigSelector:
    matchExpressions:
      - { key: machineconfiguration.openshift.io/role, operator: In, values: [worker,cnv] }
  maxUnavailable: 1
  nodeSelector:
    matchLabels:
      node-role.kubernetes.io/cnv: ""
  paused: false