apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: resource-locker-proxy-role
  namespace: resource-locker-config
rules:
  - apiGroups:
    - ""
    resources:
    - configmaps
    verbs:
    - get
    - list
    - watch
    - patch
    - update
    - create
  - apiGroups:
      - config.openshift.io
    resources:
      - proxys
    verbs:
      - get
      - list
      - watch
      - patch
      - update