apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: shot-ingress-binding
  namespace: umbrella-gitops
placementRef:
  name: shot-ingress-rule
  apiGroup: apps.open-cluster-management.io
  kind: PlacementRule
subjects:
  - name: shot-ingress-policy
    apiGroup: policy.open-cluster-management.io
    kind: Policy
