apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - inventory-sealed.yaml
  - postgres-pvc.yaml
  - ansible-tower-install-sa.yaml
  - ansible-tower-install-sa-clusterrole.yaml
  - ansible-tower-install-sa-clusterrolebinding.yaml
  - tower-install-job.yaml