apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../operators/advanced-cluster-security/base
  - central.yaml
  - namespace.yaml
  - uc2-central-tls-sealed.yaml
