apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: resource-locker-ingress-deployment-role
  namespace: resource-locker-config
rules:
- apiGroups:
  - apps
  - extensions
  resources:
  - deployment
  - deployments
  verbs:
  - list
  - get
  - watch
  - create
  - update
  - patch