apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: resource-locker-registry-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: resource-locker-registry-role
subjects:
- kind: ServiceAccount
  name: resource-locker-registry-sa
  namespace: resource-locker-config