apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: guestbook-subscription
  namespace: guestbook-app
  labels:
    app: guestbook-app
  annotations:
      apps.open-cluster-management.io/git-branch: main
      apps.open-cluster-management.io/github-path: manifests/advanced-cluster-management-apps/guestbook/guestbook/base
      apps.open-cluster-management.io/reconcile-option: merge
spec:
  channel: umbrella-gitops/umbrella-gitops
  placement:
    placementRef:
      kind: PlacementRule
      name: placement-rule-guestbook-app