apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: odf-deployment-policy
  namespace: uc2-gitops
  annotations:
    policy.open-cluster-management.io/standards: NIST-CSF
    policy.open-cluster-management.io/categories: PR.IP Information Protection Processes and Procedures
    policy.open-cluster-management.io/controls: PR.IP-1 Baseline Configuration
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: odf-namespace
      spec:
        remediationAction: enforce
        severity: High
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: v1
            kind: Namespace
            metadata:
              labels:
                openshift.io/cluster-monitoring: "true"
              name: openshift-storage
            spec: {}
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: odf-operatorgroup
      spec:
        remediationAction: enforce
        severity: High
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: operators.coreos.com/v1
            kind: OperatorGroup
            metadata:
              name: openshift-storage-operatorgroup
              namespace: openshift-storage
            spec:
              targetNamespaces:
                - openshift-storage
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: odf-subscription
      spec:
        remediationAction: enforce
        severity: High
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: operators.coreos.com/v1alpha1
            kind: Subscription
            metadata:
              labels:
                operators.coreos.com/odf-operator.openshift-storage: ""
              name: odf-operator
              namespace: openshift-storage
            spec:
              channel: stable-4.11
              installPlanApproval: Automatic
              name: odf-operator
              source: redhat-operators
              sourceNamespace: openshift-marketplace
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: odf-storagecluster
      spec:
        remediationAction: enforce
        severity: High
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: ocs.openshift.io/v1
            kind: StorageCluster
            metadata:
              annotations:
                uninstall.ocs.openshift.io/cleanup-policy: delete
                uninstall.ocs.openshift.io/mode: graceful
              name: odf-storagecluster
              namespace: openshift-storage
            spec:
              arbiter: {}
              encryption:
                kms: {}
              externalStorage: {}
              managedResources:
                cephBlockPools: {}
                cephConfig: {}
                cephDashboard: {}
                cephFilesystems: {}
                cephObjectStoreUsers: {}
                cephObjectStores: {}
              mirroring: {}
              nodeTopologies: {}
              storageDeviceSets:
              - config: {}
                count: 1
                dataPVCTemplate:
                  metadata: {}
                  spec:
                    accessModes:
                    - ReadWriteOnce
                    resources:
                      requests:
                        storage: 512Gi
                    storageClassName: gp3-csi
                    volumeMode: Block
                  status: {}
                name: ocs-deviceset-gp3-csi
                placement: {}
                portable: true
                preparePlacement: {}
                replica: 3
                resources: {}
              version: 4.11.0
