apiVersion: redhatcop.redhat.io/v1alpha1
kind: ResourceLocker
metadata:
  name: ingress-deployment-patch
  namespace: resource-locker-config
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  serviceAccountRef:
    name: resource-locker-ingress-deployment-sa
  patches:
  - targetObjectRef:
      apiVersion: apps/v1
      kind: Deployment
      namespace: open-cluster-management
      metadata:
        labels:
          helm.sh/chart: management-ingress
    patchTemplate: |
      spec:
        template:
          spec:
            containers:
            - command:
              - /management-ingress
              - --default-ssl-certificate=$(POD_NAMESPACE)/byo-ingress-tls-secret
              - --configmap=$(POD_NAMESPACE)/{{ (index . 0).metadata.name }}
              - --http-port=8080
              - --https-port=8443
              name: {{ (index . 0).metadata.name }}
            volumes:
            - name: tls-secret
              secret:
                defaultMode: 420
                secretName: byo-ingress-tls-secret
            - name: ca-tls-secret
              secret:
                defaultMode: 420
                secretName: byo-ca-cert
    sourceObjectRefs:
    - apiVersion: apps/v1
      kind: Deployment
      namespace: open-cluster-management
      metadata:
        labels:
          helm.sh/chart: management-ingress
    patchType: application/strategic-merge-patch+json
    id: ingress-deployment-patch