apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../operators/advanced-cluster-management/base
  - byo-ca-cert-sealed.yaml
  - byo-ingress-tls-sealed.yaml
  - multiclusterhub.yaml
  - observability-job.yaml
  - observability-namespace.yaml
  - observability-obc.yaml
  - umbrella-gitops-channel.yaml
  - umbrella-gitops-namespace.yaml
  - umbrella-gitops-subscription.yaml
