apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../operators/advanced-cluster-management/base
  - multiclusterhub.yaml
  - byo-ingress-tls-sealed.yaml
  - byo-ca-cert-sealed.yaml
  - ingress-deployment-patch.yaml
  - byo-certs-patch-job.yaml