apiVersion: operator.open-cluster-management.io/v1
kind: MultiClusterHub
metadata:
  name: umbrella-hub
  namespace: open-cluster-management
  annotations:
    argocd.argoproj.io/sync-wave: "4"
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  imagePullSecret: pull-secret
