apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: umbrella-gitops
  namespace: umbrella-gitops
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/github-path: manifests/advanced-cluster-management-gitops/base
    apps.open-cluster-management.io/reconcile-option: merge
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  channel: umbrella-gitops/umbrella-gitops
  placement:
    local: true
