---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: umbrella-gitops
  namespace: umbrella-gitops
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  type: GitHub
  pathname: https://github.com/nasx/umbrella-gitops.git
