apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: spark-ingress-rule
  namespace: umbrella-gitops
spec:
  clusterSelector:
    matchExpressions:
      - key: name
        operator: In
        values:
          - spark
  clusterConditions: []
