apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-shared-storage
  namespace: openshift-image-registry
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "3"
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 75Gi
  storageClassName: ocs-storagecluster-cephfs