apiVersion: redhatcop.redhat.io/v1alpha1
kind: Patch
metadata:
  name: registry-patch
  namespace: patch-operator-config
spec:
  patches:
    registry-patch:
      patchTemplate: |
        spec:
          managementState: Managed
          defaultRoute: true
          replicas: 3
          storage:
            pvc:
              claim: registry-shared-storage
          nodeSelector:
            node-role.kubernetes.io/infra: ""
      patchType: application/merge-patch+json
      targetObjectRef:
        apiVersion: imageregistry.operator.openshift.io/v1
        kind: Config
        name: cluster
  serviceAccountRef:
    name: patch-operator-registry-sa
