# AMI ID References:
# ami-00878b15766f10fbf - Microsoft Windows Server 1909 Core Containers Latest 2021.02.10
# ami-0d5f9982f029fbc14 - Red Hat CoreOS - OpenShift 4 rhcos-47.83.202102090044-0

- name: Example Playbook for machineset Role
  hosts: localhost
  roles:
    - role: machineset
      vars:
        machinesets:
          - ami: ami-0a57c1b4939e5ef5b
            blockDevices:
            - ebs:
                iops: 0
                volumeSize: 120
                volumeType: gp2
            instance_type: c5n.metal
            machine_role: worker
            machine_type: worker
            name: metal
            node_labels:
              node-role.kubernetes.io/worker: ""
            region: us-east-1
            replicas: 1
            subnet_id: subnet-04ba833e3387f0bde
            tags:
              - name: "kubernetes.io/cluster/{{ cluster_info.resources[0].status.infrastructureName }}"
                value: owned
            user_data_secret: worker-user-data
            zone: us-east-1a
