apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: advanced-cluster-management
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/compare-options: IgnoreExtraneous
  labels:
    gitops.ownedBy: cluster-config
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: cluster-config
  source:
    path: manifests/clusters/alice/advanced-cluster-management/base
    repoURL: https://github.com/nasx/umbrella-gitops.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: true