apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ansible-tower
  annotations:
    argocd.argoproj.io/sync-wave: "4"
    argocd.argoproj.io/compare-options: IgnoreExtraneous
  labels:
    gitops.ownedBy: cluster-config
spec:
  destination:
    namespace: umbrella-gitops
    server: https://kubernetes.default.svc
  project: cluster-config
  source:
    path: manifests/ansible-tower/base
    repoURL: https://github.com/nasx/umbrella-gitops.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: true