apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  labels:
    gitops.ownedBy: cluster-config
spec:
  destination:
    namespace: umbrella-gitops
    server: https://kubernetes.default.svc
  project: cluster-config
  source:
    path: manifests/clusters/alice/cluster-monitoring/base
    repoURL: https://github.com/nasx/umbrella-gitops.git
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true
