apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: network-observability
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/compare-options: IgnoreExtraneous
  labels:
    gitops.ownedBy: cluster-config
spec:
  destination:
    namespace: umbrella-gitops
    server: https://kubernetes.default.svc
  project: cluster-config
  source:
    path: manifests/clusters/alice/network-observability/base
    repoURL: https://github.com/nasx/umbrella-gitops.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
      limit: -1
