kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: ansible-runner
  namespace: ansible-runner
spec:
  runPolicy: Serial
  source:
    type: Dockerfile
    dockerfile: |
      FROM registry.access.redhat.com/ubi8/python-38
      USER 0
      RUN dnf update -y && \
          pip install --upgrade pip && \
          pip install openshift && \
          pip install jmespath && \
          pip install netaddr && \
          pip install ansible==2.9.* && \
          curl -sL https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux.tar.gz | tar -C /usr/local/bin -xvzf - oc kubectl
      USER 1001
  strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: DockerImage
        name: registry.access.redhat.com/ubi8/python-38
  triggers:
    - type: ConfigChange
  output:
    to:
      kind: ImageStreamTag
      name: ansible-runner:latest