apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: quay-operator
  namespace: openshift-operators
spec:
  channel: stable-3.7
  installPlanApproval: Automatic
  name: quay-operator
  source: redhat-operators 
  sourceNamespace: openshift-marketplace
