apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: spark-shot-registry-whitelist
  namespace: umbrella-gitops
  annotations:
    policy.open-cluster-management.io/standards: NIST-CSF
    policy.open-cluster-management.io/categories: PR.IP Information Protection Processes and Procedures
    policy.open-cluster-management.io/controls: PR.IP-1 Baseline Configuration
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: policy-cluster-image-config
      spec:
        remediationAction: enforce
        severity: High
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: config.openshift.io/v1
            kind: Image
            metadata:
              name: cluster
            spec:
              registrySources:
                allowedRegistries:
                  - image-registry.openshift-image-registry.svc
                  - quay.io/openshift-release-dev
                  - registry.redhat.io