apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-limit-cluster-admin
  namespace: umbrella-gitops
  annotations:
    policy.open-cluster-management.io/standards: NIST-CSF
    policy.open-cluster-management.io/categories: PR.AC Identity Management and Access Control
    policy.open-cluster-management.io/controls: PR.AC-4 Access Control
spec:
  remediationAction: inform
  disabled: false
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: IamPolicy
      metadata:
        name: policy-limit-cluster-admin
      spec:
        severity: medium
        namespaceSelector:
          include: ["*"]
          exclude: ["kube-*", "openshift-*"]
        remediationAction: inform
        maxClusterRoleBindingUsers: 5
