apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: patch-operator-node-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: patch-operator-node-role
subjects:
- kind: ServiceAccount
  name: patch-operator-node-sa
  namespace: patch-operator-config
