apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: patch-operator-ingress-role
  namespace: patch-operator-config
rules:
- apiGroups:
  - operator.openshift.io
  resources:
  - ingresscontroller
  - ingresscontrollers
  verbs:
  - list
  - get
  - watch
  - create
  - update
  - patch
