apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: patch-operator-oauth-role
  namespace: patch-operator-config
rules:
- apiGroups:
  - config.openshift.io
  resources:
  - oauth
  - oauths
  verbs:
  - list
  - get
  - watch
  - create
  - update
  - patch
