apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: patch-operator-registry-role
  namespace: patch-operator-config
rules:
- apiGroups:
  - imageregistry.operator.openshift.io
  resources:
  - config
  - configs
  verbs:
  - list
  - get
  - watch
  - create
  - update
  - patch
