apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: patch-operator-node-role
  namespace: patch-operator-config
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - node
  verbs:
  - list
  - get
  - watch
  - create
  - update
  - patch
