apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: patch-operator-apiserver-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: patch-operator-apiserver-role
subjects:
- kind: ServiceAccount
  name: patch-operator-apiserver-sa
  namespace: patch-operator-config
