apiVersion: redhatcop.redhat.io/v1alpha1
kind: ResourceLocker
metadata:
  name: oauth-patch
  namespace: resource-locker-config
spec:
  serviceAccountRef:
    name: resource-locker-oauth-sa
  patches:
  - targetObjectRef:
      apiVersion: config.openshift.io/v1
      kind: OAuth
      name: cluster
    patchTemplate: |
      spec:
        identityProviders:
        - name: "Umbrella IdM"
          mappingMethod: claim
          type: LDAP
          ldap:
            attributes:
              id:
              - dn
              email:
              - mail
              name:
              - cn
              preferredUsername:
              - uid
            bindDN: uid=ocp-service-account,cn=users,cn=accounts,dc=umbrella,dc=local
            bindPassword:
              name: oauth-ldap-bind-secret
            ca:
              name: oauth-ldap-ca-config-map
            insecure: false
            url: ldap://idm1.lab.uc2.io/cn=users,cn=accounts,dc=umbrella,dc=local?uid
    patchType: application/merge-patch+json
    id: oauth-patch