apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: pacman-subscription
  namespace: pacman-app
  labels:
    app: pacman-app
  annotations:
      apps.open-cluster-management.io/git-branch: main
      apps.open-cluster-management.io/github-path: manifests/advanced-cluster-management-apps/pacman/pacman/base
      apps.open-cluster-management.io/reconcile-option: merge
spec:
  channel: umbrella-gitops/umbrella-gitops
  placement:
    placementRef:
      kind: PlacementRule
      name: placement-rule-pacman-app