apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: thick-ssd
parameters:
  diskformat: zeroedthick
  datastore: r440-1-ssd-local
provisioner: kubernetes.io/vsphere-volume
reclaimPolicy: Delete
volumeBindingMode: Immediate
