apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: thick-nvme
parameters:
  diskformat: zeroedthick
  datastore: pool-nvme-vms
provisioner: kubernetes.io/vsphere-volume
reclaimPolicy: Delete
volumeBindingMode: Immediate