apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: thick-spinning
parameters:
  diskformat: zeroedthick
  datastore: pool-spinning-vms
provisioner: kubernetes.io/vsphere-volume
reclaimPolicy: Delete
volumeBindingMode: Immediate
